@import gg.jte.Content
@param Content content

<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Пользователи</title>
    </head>
    <body>
        <header>
            <p><a href="/">На главную</a></p>
            <p><a href="/users">К списку пользователей</a></p>
        </header>
        <div>
            ${content}
        </div>
        <footer>
            <p>https://github.com/Iliatar/ 2024</p>
        </footer>
    </body>
</html>
